// Obtener los elementos del DOM
const titulo = document.querySelector('.titulo');
const presentacionservicios = document.querySelector('.presentacionservicios');
const boton1 = document.querySelector('#boton1');
const boton2 = document.querySelector('#boton2');
const boton3 = document.querySelector('#boton3');
const boton4 = document.querySelector('#boton4');
const boton5 = document.querySelector('#boton5');
const boton6 = document.querySelector('#boton6');
const boton12 = document.querySelector('#boton12');
const boton22 = document.querySelector('#boton22');
const boton32 = document.querySelector('#boton32');
const boton42 = document.querySelector('#boton42');
const boton52 = document.querySelector('#boton52');
const boton62 = document.querySelector('#boton62');
const informacion =  document.querySelector('.informacion');
const endoponcia =  document.querySelector('.endoponcia');
const titulo1 =  document.querySelector('.titulo1');
const titulo2 =  document.querySelector('.titulo2');
const titulo3 =  document.querySelector('.titulo3');
const titulo4 =  document.querySelector('.titulo4');
const titulo5 =  document.querySelector('.titulo5');
const titulo6 =  document.querySelector('.titulo6');
const texto1 =  document.querySelector('.texto1');
const texto2 =  document.querySelector('.texto2');
const texto3 =  document.querySelector('.texto3');
const texto4 =  document.querySelector('.texto4');
const texto5 =  document.querySelector('.texto5');
const texto6 =  document.querySelector('.texto6');
// Mostrar el formulario 1 de forma predeterminada
//flex = mostrar  ||  none =ocultar || solo titulo= block
//boton12.classList.add('btnactivo');
titulo.style.display = 'block';
presentacionservicios.style.display = 'flex';
endoponcia.style.display = 'none';
informacion.style.display = 'none';

// Ocultar el formulario 1 y mostrar el formulario 2 cuando se haga clic en el botón "Registro de tu local"
boton1.addEventListener('click', function() {
  boton12.classList.add('btnactivo');
  boton22.classList.remove('btnactivo');
  boton32.classList.remove('btnactivo');
  boton42.classList.remove('btnactivo');
  boton52.classList.remove('btnactivo');
  boton62.classList.remove('btnactivo');
  titulo.style.display = 'none';
  presentacionservicios.style.display = 'none';
  endoponcia.style.display = 'flex';
  informacion.style.display = 'flex';
  titulo1.style.display = 'block';
  titulo2.style.display = 'none';
  titulo3.style.display = 'none';
  titulo4.style.display = 'none';
  titulo5.style.display = 'none';
  titulo6.style.display = 'none';
  texto1.style.display = 'block';
  texto2.style.display = 'none';
  texto3.style.display = 'none';
  texto4.style.display = 'none';
  texto5.style.display = 'none';
  texto6.style.display = 'none';
});

boton2.addEventListener('click', function() {
  boton12.classList.remove('btnactivo');
  boton22.classList.add('btnactivo');
  boton32.classList.remove('btnactivo');
  boton42.classList.remove('btnactivo');
  boton52.classList.remove('btnactivo');
  boton62.classList.remove('btnactivo');
  titulo.style.display = 'none';
  presentacionservicios.style.display = 'none';
  endoponcia.style.display = 'flex';
  informacion.style.display = 'flex';
  titulo1.style.display = 'none';
  titulo2.style.display = 'block';
  titulo3.style.display = 'none';
  titulo4.style.display = 'none';
  titulo5.style.display = 'none';
  titulo6.style.display = 'none';
  texto1.style.display = 'none';
  texto2.style.display = 'block';
  texto3.style.display = 'none';
  texto4.style.display = 'none';
  texto5.style.display = 'none';
  texto6.style.display = 'none';
});
boton3.addEventListener('click', function() {
  boton12.classList.remove('btnactivo');
  boton22.classList.remove('btnactivo');
  boton32.classList.add('btnactivo');
  boton42.classList.remove('btnactivo');
  boton52.classList.remove('btnactivo');
  boton62.classList.remove('btnactivo');
  titulo.style.display = 'none';
  presentacionservicios.style.display = 'none';
  endoponcia.style.display = 'flex';
  informacion.style.display = 'flex';
  titulo1.style.display = 'none';
  titulo2.style.display = 'none';
  titulo3.style.display = 'block';
  titulo4.style.display = 'none';
  titulo5.style.display = 'none';
  titulo6.style.display = 'none';
  texto1.style.display = 'none';
  texto2.style.display = 'none';
  texto3.style.display = 'block';
  texto4.style.display = 'none';
  texto5.style.display = 'none';
  texto6.style.display = 'none';
});
boton4.addEventListener('click', function() {
  boton12.classList.remove('btnactivo');
  boton22.classList.remove('btnactivo');
  boton32.classList.remove('btnactivo');
  boton42.classList.add('btnactivo');
  boton52.classList.remove('btnactivo');
  boton62.classList.remove('btnactivo');
  titulo.style.display = 'none';
  presentacionservicios.style.display = 'none';
  endoponcia.style.display = 'flex';
  informacion.style.display = 'flex';
  titulo1.style.display = 'none';
  titulo2.style.display = 'none';
  titulo3.style.display = 'none';
  titulo4.style.display = 'block';
  titulo5.style.display = 'none';
  titulo6.style.display = 'none';
  texto1.style.display = 'none';
  texto2.style.display = 'none';
  texto3.style.display = 'none';
  texto4.style.display = 'block';
  texto5.style.display = 'none';
  texto6.style.display = 'none';
});
boton5.addEventListener('click', function() {
  boton12.classList.remove('btnactivo');
  boton22.classList.remove('btnactivo');
  boton32.classList.remove('btnactivo');
  boton42.classList.remove('btnactivo');
  boton52.classList.add('btnactivo');
  boton62.classList.remove('btnactivo');
  titulo.style.display = 'none';
  presentacionservicios.style.display = 'none';
  endoponcia.style.display = 'flex';
  informacion.style.display = 'flex';
  titulo1.style.display = 'none';
  titulo2.style.display = 'none';
  titulo3.style.display = 'none';
  titulo4.style.display = 'none';
  titulo5.style.display = 'block';
  titulo6.style.display = 'none';
  texto1.style.display = 'none';
  texto2.style.display = 'none';
  texto3.style.display = 'none';
  texto4.style.display = 'none';
  texto5.style.display = 'block';
  texto6.style.display = 'none';
});
boton6.addEventListener('click', function() {
  boton12.classList.remove('btnactivo');
  boton22.classList.remove('btnactivo');
  boton32.classList.remove('btnactivo');
  boton42.classList.remove('btnactivo');
  boton52.classList.remove('btnactivo');
  boton62.classList.add('btnactivo');
  titulo.style.display = 'none';
  presentacionservicios.style.display = 'none';
  endoponcia.style.display = 'flex';
  informacion.style.display = 'flex';
  titulo1.style.display = 'none';
  titulo2.style.display = 'none';
  titulo3.style.display = 'none';
  titulo4.style.display = 'none';
  titulo5.style.display = 'none';
  titulo6.style.display = 'block';
  texto1.style.display = 'none';
  texto2.style.display = 'none';
  texto3.style.display = 'none';
  texto4.style.display = 'none';
  texto5.style.display = 'none';
  texto6.style.display = 'block';
});


//subbotones
boton12.addEventListener('click', function() {
  boton12.classList.add('btnactivo');
  boton22.classList.remove('btnactivo');
  boton32.classList.remove('btnactivo');
  boton42.classList.remove('btnactivo');
  boton52.classList.remove('btnactivo');
  boton62.classList.remove('btnactivo');
  titulo.style.display = 'none';
  presentacionservicios.style.display = 'none';
  endoponcia.style.display = 'flex';
  informacion.style.display = 'flex';
  titulo1.style.display = 'block';
  titulo2.style.display = 'none';
  titulo3.style.display = 'none';
  titulo4.style.display = 'none';
  titulo5.style.display = 'none';
  titulo6.style.display = 'none';
  texto1.style.display = 'block';
  texto2.style.display = 'none';
  texto3.style.display = 'none';
  texto4.style.display = 'none';
  texto5.style.display = 'none';
  texto6.style.display = 'none';
});
boton22.addEventListener('click', function() {
  boton12.classList.remove('btnactivo');
  boton22.classList.add('btnactivo');
  boton32.classList.remove('btnactivo');
  boton42.classList.remove('btnactivo');
  boton52.classList.remove('btnactivo');
  boton62.classList.remove('btnactivo');
  titulo.style.display = 'none';
  presentacionservicios.style.display = 'none';
  endoponcia.style.display = 'flex';
  informacion.style.display = 'flex';
  titulo1.style.display = 'none';
  titulo2.style.display = 'block';
  titulo3.style.display = 'none';
  titulo4.style.display = 'none';
  titulo5.style.display = 'none';
  titulo6.style.display = 'none';
  texto1.style.display = 'none';
  texto2.style.display = 'block';
  texto3.style.display = 'none';
  texto4.style.display = 'none';
  texto5.style.display = 'none';
  texto6.style.display = 'none';
});
boton32.addEventListener('click', function() {
  boton12.classList.remove('btnactivo');
  boton22.classList.remove('btnactivo');
  boton32.classList.add('btnactivo');
  boton42.classList.remove('btnactivo');
  boton52.classList.remove('btnactivo');
  boton62.classList.remove('btnactivo');
  titulo.style.display = 'none';
  presentacionservicios.style.display = 'none';
  endoponcia.style.display = 'flex';
  informacion.style.display = 'flex';
  titulo1.style.display = 'none';
  titulo2.style.display = 'none';
  titulo3.style.display = 'block';
  titulo4.style.display = 'none';
  titulo5.style.display = 'none';
  titulo6.style.display = 'none';
  texto1.style.display = 'none';
  texto2.style.display = 'none';
  texto3.style.display = 'block';
  texto4.style.display = 'none';
  texto5.style.display = 'none';
  texto6.style.display = 'none';
});
boton42.addEventListener('click', function() {
  boton12.classList.remove('btnactivo');
  boton22.classList.remove('btnactivo');
  boton32.classList.remove('btnactivo');
  boton42.classList.add('btnactivo');
  boton52.classList.remove('btnactivo');
  boton62.classList.remove('btnactivo');
  titulo.style.display = 'none';
  presentacionservicios.style.display = 'none';
  endoponcia.style.display = 'flex';
  informacion.style.display = 'flex';
  titulo1.style.display = 'none';
  titulo2.style.display = 'none';
  titulo3.style.display = 'none';
  titulo4.style.display = 'block';
  titulo5.style.display = 'none';
  titulo6.style.display = 'none';
  texto1.style.display = 'none';
  texto2.style.display = 'none';
  texto3.style.display = 'none';
  texto4.style.display = 'block';
  texto5.style.display = 'none';
  texto6.style.display = 'none';
});
boton52.addEventListener('click', function() {
  boton12.classList.remove('btnactivo');
  boton22.classList.remove('btnactivo');
  boton32.classList.remove('btnactivo');
  boton42.classList.remove('btnactivo');
  boton52.classList.add('btnactivo');
  boton62.classList.remove('btnactivo');
  titulo.style.display = 'none';
  presentacionservicios.style.display = 'none';
  endoponcia.style.display = 'flex';
  informacion.style.display = 'flex';
  titulo1.style.display = 'none';
  titulo2.style.display = 'none';
  titulo3.style.display = 'none';
  titulo4.style.display = 'none';
  titulo5.style.display = 'block';
  titulo6.style.display = 'none';
  texto1.style.display = 'none';
  texto2.style.display = 'none';
  texto3.style.display = 'none';
  texto4.style.display = 'none';
  texto5.style.display = 'block';
  texto6.style.display = 'none';
});
boton62.addEventListener('click', function() {
  boton12.classList.remove('btnactivo');
  boton22.classList.remove('btnactivo');
  boton32.classList.remove('btnactivo');
  boton42.classList.remove('btnactivo');
  boton52.classList.remove('btnactivo');
  boton62.classList.add('btnactivo');
  titulo.style.display = 'none';
  presentacionservicios.style.display = 'none';
  endoponcia.style.display = 'flex';
  informacion.style.display = 'flex';
  titulo1.style.display = 'none';
  titulo2.style.display = 'none';
  titulo3.style.display = 'none';
  titulo4.style.display = 'none';
  titulo5.style.display = 'none';
  titulo6.style.display = 'block';
  texto1.style.display = 'none';
  texto2.style.display = 'none';
  texto3.style.display = 'none';
  texto4.style.display = 'none';
  texto5.style.display = 'none';
  texto6.style.display = 'block';
});




